/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'carId' : IDL.Nat,
  'date' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'timeSlot' : IDL.Text,
});
export const CarInput = IDL.Record({
  'emi' : IDL.Nat,
  'status' : IDL.Text,
  'model' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'ownership' : IDL.Text,
  'slug' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'transmission' : IDL.Text,
  'fuelType' : IDL.Text,
  'kmDriven' : IDL.Nat,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const Car = IDL.Record({
  'id' : IDL.Nat,
  'emi' : IDL.Nat,
  'status' : IDL.Text,
  'model' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'ownership' : IDL.Text,
  'slug' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'transmission' : IDL.Text,
  'fuelType' : IDL.Text,
  'kmDriven' : IDL.Nat,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'images' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBooking' : IDL.Func([Booking], [Booking], []),
  'addCar' : IDL.Func([CarInput], [Car], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCar' : IDL.Func([IDL.Nat], [], []),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCarBySlug' : IDL.Func([IDL.Text], [Car], ['query']),
  'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getFeaturedCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCarAsSold' : IDL.Func([IDL.Nat], [Car], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateCar' : IDL.Func([IDL.Nat, CarInput], [Car], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'carId' : IDL.Nat,
    'date' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'timeSlot' : IDL.Text,
  });
  const CarInput = IDL.Record({
    'emi' : IDL.Nat,
    'status' : IDL.Text,
    'model' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'ownership' : IDL.Text,
    'slug' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'transmission' : IDL.Text,
    'fuelType' : IDL.Text,
    'kmDriven' : IDL.Nat,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const Car = IDL.Record({
    'id' : IDL.Nat,
    'emi' : IDL.Nat,
    'status' : IDL.Text,
    'model' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'ownership' : IDL.Text,
    'slug' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'transmission' : IDL.Text,
    'fuelType' : IDL.Text,
    'kmDriven' : IDL.Nat,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBooking' : IDL.Func([Booking], [Booking], []),
    'addCar' : IDL.Func([CarInput], [Car], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCar' : IDL.Func([IDL.Nat], [], []),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCarBySlug' : IDL.Func([IDL.Text], [Car], ['query']),
    'getCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getFeaturedCars' : IDL.Func([], [IDL.Vec(Car)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCarAsSold' : IDL.Func([IDL.Nat], [Car], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateCar' : IDL.Func([IDL.Nat, CarInput], [Car], []),
  });
};

export const init = ({ IDL }) => { return []; };